// <auto-generated />
using System;
using CafPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927124551_AddNominationBlockers")]
    partial class AddNominationBlockers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CafPortal.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Aliases")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cftl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPoc")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectManager")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionArchitect")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StrategicFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tpid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountName");

                    b.HasIndex("Region");

                    b.HasIndex("Tpid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.AccountAlias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardAccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AliasId");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("AccountAliases");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Auth.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.CapacityFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapacityStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("UtilizationPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("CapacityFacts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.CapacityConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("OverloadedThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("WarningThreshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("CapacityConfigurations");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RegionConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RoleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Granted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleConfigurationId", "PermissionKey")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.SegmentConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.SkillConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.StrategicAccountConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExecutiveVisibilityFlag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RiskFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StrategicFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountName");

                    b.ToTable("StrategicAccountConfigurations");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.ToolConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.EngagementFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("MeetingName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date");

                    b.HasIndex("ResourceId");

                    b.ToTable("EngagementFacts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.GateDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GateDefinitions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.GateItemDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GateDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponsibleRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubStage")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GateDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("GateItemDefinitions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.NominationBlocker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BlockedSinceUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClockStopped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedResolutionUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GateItemDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NominationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaisedBy")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NominationId", "ResolvedUtc");

                    b.ToTable("NominationBlockers");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.NominationGateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GateItemDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NominationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ref")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GateItemDefinitionId");

                    b.HasIndex("NominationId", "GateItemDefinitionId")
                        .IsUnique();

                    b.ToTable("NominationGateItems");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ImportChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.ToTable("ImportChanges");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Added")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unchanged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Withdrawn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.LeaveFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaveDate");

                    b.HasIndex("ResourceId", "LeaveDate");

                    b.ToTable("LeaveFacts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Nomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BlockedSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("CftlPrimary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAutomationUsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsToolAttached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MigrationStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeOfAccess")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NnrAcr")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NominatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerName")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMigrationPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCoordinator")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionArchitect")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StageAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAcr")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalCores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExternalTaskId");

                    b.HasIndex("Status");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.NominationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NominationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("NominationId", "ResourceId")
                        .IsUnique();

                    b.ToTable("NominationResources");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.OwnershipHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ChangedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("OwnershipHistory");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ParkedAccount", b =>
                {
                    b.Property<int>("ParkedAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aliases")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cftl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NominationIds")
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ParkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceLinks")
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionArchitect")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StrategicFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tpid")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ParkedAccountId");

                    b.ToTable("ParkedAccounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.PerformanceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Attitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CommunicationVerbal")
                        .HasColumnType("REAL");

                    b.Property<double?>("CommunicationWritten")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OfferingUnderstanding")
                        .HasColumnType("REAL");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProcessUnderstanding")
                        .HasColumnType("REAL");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportingManager")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("PersonName", "ReviewDate");

                    b.ToTable("PerformanceReviews");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("ExperienceYears")
                        .HasColumnType("REAL");

                    b.Property<string>("Mobile")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimarySkill")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Psid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Separated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] <> ''");

                    b.HasIndex("Psid");

                    b.HasIndex("Region");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ResourceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ResourceId", "AccountId")
                        .IsUnique();

                    b.ToTable("ResourceAccounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.WaveLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NominationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("NominationId");

                    b.ToTable("WaveLinks");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.CapacityFact", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RolePermission", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Configuration.RoleConfiguration", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.StrategicAccountConfiguration", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.EngagementFact", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany("EngagementFacts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany("EngagementFacts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.GateItemDefinition", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Governance.GateDefinition", "Gate")
                        .WithMany("Items")
                        .HasForeignKey("GateDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.NominationGateItem", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Governance.GateItemDefinition", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("GateItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ImportChange", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.ImportRun", "Run")
                        .WithMany("Changes")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.LeaveFact", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany("LeaveFacts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Nomination", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.NominationResource", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Nomination", "Nomination")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomination");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.OwnershipHistory", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany("OwnershipHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ResourceAccount", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany("ResourceAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany("ResourceAccounts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.WaveLink", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafPortal.Domain.Entities.Nomination", "Nomination")
                        .WithMany("WaveLinks")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Nomination");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Account", b =>
                {
                    b.Navigation("EngagementFacts");

                    b.Navigation("OwnershipHistory");

                    b.Navigation("ResourceAccounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RoleConfiguration", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Governance.GateDefinition", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ImportRun", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Nomination", b =>
                {
                    b.Navigation("ResourceAssignments");

                    b.Navigation("WaveLinks");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Resource", b =>
                {
                    b.Navigation("EngagementFacts");

                    b.Navigation("LeaveFacts");

                    b.Navigation("ResourceAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
