// <auto-generated />
using System;
using CafPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CafPortal.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StrategicFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tpid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountName");

                    b.HasIndex("Region");

                    b.HasIndex("Tpid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.AccountAlias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardAccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AliasId");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("AccountAliases");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.CapacityFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapacityStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("UtilizationPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("CapacityFacts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.CapacityConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("OverloadedThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("WarningThreshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("CapacityConfigurations");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RegionConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RoleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Granted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleConfigurationId", "PermissionKey")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.StrategicAccountConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExecutiveVisibilityFlag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RiskFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StrategicFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountName");

                    b.ToTable("StrategicAccountConfigurations");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.EngagementFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("MeetingName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date");

                    b.HasIndex("ResourceId");

                    b.ToTable("EngagementFacts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.LeaveFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaveDate");

                    b.HasIndex("ResourceId", "LeaveDate");

                    b.ToTable("LeaveFacts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Nomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CftlPrimary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCoordinator")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionArchitect")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Status");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DedicatedFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("ExperienceYears")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimarySkill")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Psid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.HasIndex("Email");

                    b.HasIndex("Psid");

                    b.HasIndex("Region");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ResourceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ResourceId", "AccountId")
                        .IsUnique();

                    b.ToTable("ResourceAccounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.CapacityFact", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RolePermission", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Configuration.RoleConfiguration", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.StrategicAccountConfiguration", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.EngagementFact", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany("EngagementFacts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany("EngagementFacts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.LeaveFact", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany("LeaveFacts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Nomination", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.ResourceAccount", b =>
                {
                    b.HasOne("CafPortal.Domain.Entities.Account", "Account")
                        .WithMany("ResourceAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafPortal.Domain.Entities.Resource", "Resource")
                        .WithMany("ResourceAccounts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Account", b =>
                {
                    b.Navigation("EngagementFacts");

                    b.Navigation("ResourceAccounts");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Configuration.RoleConfiguration", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CafPortal.Domain.Entities.Resource", b =>
                {
                    b.Navigation("EngagementFacts");

                    b.Navigation("LeaveFacts");

                    b.Navigation("ResourceAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
